version: '3'

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS= go build -o bin/gopher-cli main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS= go run main.go

  clean:
    desc: Remove all retrieved *.png files
    cmds:
      - rm *.png
